<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>1.0.15</Version>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>coer91.NET.Files</PackageId>
    <Title>coer91.NET.Files</Title>
    <Authors>Christian Omar Escamilla Rodríguez</Authors>
    <Description>Plugin for dotnet 10</Description>
    <PackageIcon>coer91.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/coer91/coer91.DotNet</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="itext" Version="9.6.0" />
    <PackageReference Include="itext.bouncy-castle-adapter" Version="9.6.0" />
    <PackageReference Include="itext.pdfhtml" Version="6.3.2" />
    <PackageReference Include="NetBarcode" Version="1.8.3" />
    <PackageReference Include="QRCoder.Core" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\coer91.NET\coer91.NET.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="coer91.png">
      <PackagePath>\</PackagePath>
      <Pack>True</Pack>
    </None>
    <None Update="LICENSE">
      <PackagePath>\</PackagePath>
      <Pack>True</Pack>
    </None>
    <None Update="README.md">
      <PackagePath>\</PackagePath>
      <Pack>True</Pack>
    </None>
  </ItemGroup> 
</Project>